# mkdocs.yml
site_name: "hello-vibe"
site_url: https://hello-vibe.311factory.top/
repo_url: https://github.com/jspi-fu/hello-vibe
repo_name: jspi-fu/hello-vibe
theme:
  name: shadcn
  show_title: true
  show_stargazers: true
  pygments_style:
    light: shadcn-light
    dark: github-dark
  icon: assets/logo.svg
  topbar_sections: false
  show_datetime: false
  katex_options: {}

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true

extra_javascript:
  - assets/custom-favicon.js

markdown_extensions:
  - admonition
  - codehilite
  - fenced_code
  - footnotes
  - pymdownx.blocks.details
  - pymdownx.blocks.tab
  - pymdownx.progressbar
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true
  - attr_list